<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Frecuencias extends \Entity\Frecuencias implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdFrecuencia()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idFrecuencia"];
        }
        $this->__load();
        return parent::getIdFrecuencia();
    }

    public function getIdCategoriasFrecuencia()
    {
        $this->__load();
        return parent::getIdCategoriasFrecuencia();
    }

    public function getPeriodicidad()
    {
        $this->__load();
        return parent::getPeriodicidad();
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setIdCategoriasFrecuencia(\Entity\CategoriasFrecuencia $idCategoriasFrecuencia)
    {
        $this->__load();
        return parent::setIdCategoriasFrecuencia($idCategoriasFrecuencia);
    }

    public function setPeriodicidad($periodicidad)
    {
        $this->__load();
        return parent::setPeriodicidad($periodicidad);
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idFrecuencia', 'periodicidad', 'nombre', 'idCategoriasFrecuencia');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}